//==============================================================================
// Generated on: 2023-12-28 01:17:04.497225
// Generated by: _convert.py in this directory
// Source: https://github.com/betaflight/unified-targets
// Board name: HYBRIDG4
// Manufacturer ID: NERC
//==============================================================================

//LED:
const int HW_PIN_LED      = C15;
#define LED_ON 0 //low = on

//Battery voltage divider:
const int HW_PIN_BAT_ADC  = A00;
const int HW_PIN_BAT_CURR = A01;

//GPS: (SERIAL1)
const int HW_PIN_GPS_RX   = A10;
const int HW_PIN_GPS_TX   = A09;
HardwareSerial gps_Serial(HW_PIN_GPS_RX, HW_PIN_GPS_TX);

//RC Receiver: (SERIAL3)
const int HW_PIN_RCIN_RX  = B11;
const int HW_PIN_RCIN_TX  = B10;
HardwareSerial *rcin_Serial = new HardwareSerial(HW_PIN_RCIN_RX, HW_PIN_RCIN_TX);

//IMU:
const int HW_PIN_IMU_INT  = C04;

//I2C: (I2C1)
const int HW_PIN_I2C_SDA  = A15;
const int HW_PIN_I2C_SCL  = B07;
typedef TwoWire HW_WIRETYPE; //define the class to use for I2C
HW_WIRETYPE *i2c = &Wire; //&Wire or &Wire1

//SPI: (SPI1)
const int HW_PIN_SPI_MISO = A06;
const int HW_PIN_SPI_CS   = A04;
const int HW_PIN_SPI_SCLK = A05;
const int HW_PIN_SPI_MOSI = A07;
SPIClass *spi = &SPI;

//Outputs:
#define HW_OUT_COUNT 4
const int8_t HW_PIN_OUT[HW_OUT_COUNT] = {PB0,PB1,PB2,PB3};


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32G47X (SG47) 4.3.0 Apr 27 2021 / 03:49:09 (e228d797c) MSP API: 1.44

board_name HYBRIDG4
manufacturer_id NERC

# resources
resource BEEPER 1 C14
resource MOTOR 1 B00
resource MOTOR 2 B01
resource MOTOR 3 B02
resource MOTOR 4 B03
resource PPM 1 A02
resource LED_STRIP 1 A08
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 3 B10
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 3 B11
resource I2C_SCL 1 A15
resource I2C_SDA 1 B07
resource LED 1 C15
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 C10
resource SPI_MISO 1 A06
resource SPI_MISO 2 B14
resource SPI_MISO 3 C11
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 B15
resource SPI_MOSI 3 B05
resource ESCSERIAL 1 C06
resource CAMERA_CONTROL 1 B06
resource ADC_BATT 1 A00
resource ADC_CURR 1 A01
resource FLASH_CS 1 B09
resource OSD_CS 1 B12
resource GYRO_EXTI 1 C04
resource GYRO_CS 1 A04

# timer
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer B02 AF2
# pin B02: TIM5 CH1 (AF2)
timer B03 AF1
# pin B03: TIM2 CH2 (AF1)
timer A08 AF6
# pin A08: TIM1 CH1 (AF6)
timer B06 AF2
# pin B06: TIM4 CH1 (AF2)
timer A02 AF9
# pin A02: TIM15 CH1 (AF9)

# dma
dma ADC 1 12
# ADC 1: DMA2 Channel 5 Request 5
dma ADC 4 0
# ADC 4: DMA1 Channel 1 Request 38
dma ADC 5 0
# ADC 5: DMA1 Channel 1 Request 39
dma TIMUP 3 0
# TIMUP 3: DMA1 Channel 1 Request 65
dma TIMUP 4 0
# TIMUP 4: DMA1 Channel 1 Request 71
dma TIMUP 5 0
# TIMUP 5: DMA1 Channel 1 Request 76
dma pin B00 0
# pin B00: DMA1 Channel 1 Request 63
dma pin B01 1
# pin B01: DMA1 Channel 2 Request 64
dma pin B02 2
# pin B02: DMA1 Channel 3 Request 72
dma pin B03 3
# pin B03: DMA1 Channel 4 Request 57
dma pin A08 8
# pin A08: DMA2 Channel 1 Request 42
dma pin B06 0
# pin B06: DMA1 Channel 1 Request 67
dma pin A02 0
# pin A02: DMA1 Channel 1 Request 78

# serial
serial 0 2048 115200 57600 0 115200
serial 1 64 115200 57600 0 115200
serial 2 1024 115200 57600 0 115200

# master
set baro_bustype = I2C
set baro_i2c_device = 1
set blackbox_device = SPIFLASH
set beeper_inversion = ON
set beeper_od = OFF
set system_hse_mhz = 8
set max7456_spi_bus = 2
set led_inversion = 1
set flash_spi_bus = 3
set pid_process_denom = 2
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_align_yaw = 2700

*/
