/*==============================================================================
Generated on: 2025-06-11 20:35:53.794496
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: ALIENFLIGHTF4
Manufacturer ID: AFNG

//copy this line to madflight.ino to use this flight controller
#define MF_BOARD "brd/betaflight/AFNG-ALIENFLIGHTF4.h"

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out, or use madflight_config to override.
==============================================================================*/

#define MF_BOARD_NAME "BETAFLIGHT-AFNG-ALIENFLIGHTF4"
#define MF_MCU_NAME "STM32F405"

const char madflight_board[] = R""(
imu_bus_type SPI
imu_gizmo MPU9250 // #define USE_GYRO_SPI_MPU9250
imu_gizmo MPU6500 // #define USE_GYRO_SPI_MPU6500
mag_gizmo SPI_AK8963 // #define USE_MAG_SPI_AK8963
// resource BEEPER 1 C13
pin_out0 PB8 // resource MOTOR 1 B08
pin_out1 PB9 // resource MOTOR 2 B09
pin_out2 PA0 // resource MOTOR 3 A00
pin_out3 PA1 // resource MOTOR 4 A01
pin_out4 PC6 // resource MOTOR 5 C06
pin_out5 PC7 // resource MOTOR 6 C07
pin_out6 PC8 // resource MOTOR 7 C08
pin_out7 PC9 // resource MOTOR 8 C09
pin_rcl_ppm PA8 // resource PPM 1 A08
// resource PWM 1 A08
// resource PWM 2 B00
// resource PWM 3 B01
// resource PWM 4 B14
// resource PWM 5 B15
// resource LED_STRIP 1 B15
pin_ser0_tx PA9 // resource SERIAL_TX 1 A09
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser3_tx PC10 // resource SERIAL_TX 4 C10
pin_ser0_rx PA10 // resource SERIAL_RX 1 A10
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_ser3_rx PC11 // resource SERIAL_RX 4 C11
pin_ser1_inv PC15 // resource INVERTER 2 C15
pin_i2c0_scl PB6 // resource I2C_SCL 1 B06
pin_i2c0_sda PB7 // resource I2C_SDA 1 B07
pin_led PC12 // resource LED 1 C12
// resource LED 2 D02
// resource RX_BIND 1 B02
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi2_sclk PB3 // resource SPI_SCK 3 B03
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi1_miso PC2 // resource SPI_MISO 2 C02
pin_spi2_miso PB4 // resource SPI_MISO 3 B04
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi1_mosi PC3 // resource SPI_MOSI 2 C03
pin_spi2_mosi PB5 // resource SPI_MOSI 3 B05
// resource ESCSERIAL 1 A08
pin_bat_v PC0 // resource ADC_BATT 1 C00
bat_gizmo ADC
// resource ADC_RSSI 1 C04
pin_bat_i PC1 // resource ADC_CURR 1 C01
bat_gizmo ADC
// resource ADC_EXT 1 C05
pin_bbx_cs PB10 // resource SDCARD_CS 1 B10
bbx_gizmo SDSPI
// resource SDCARD_DETECT 1 B11
// resource FLASH_CS 1 B12
pin_imu_int PC14 // resource GYRO_EXTI 1 C14
pin_imu_cs PA4 // resource GYRO_CS 1 A04
// set align_mag = CW180FLIP
// set mag_align_pitch = 1800
// set mag_align_yaw = 1800
// set mag_bustype = I2C
mag_i2c_bus 0 // set mag_i2c_device = 1
// set baro_bustype = I2C
bar_i2c_bus 0 // set baro_i2c_device = 1
// set serialrx_provider = SPEK2048
// set spektrum_sat_bind = 9
// set blackbox_device = SDCARD
// set dshot_burst = ON
// set battery_meter = ADC
// set beeper_inversion = ON
// set beeper_od = OFF
// set sdcard_detect_inverted = ON
// set sdcard_mode = SPI
bbx_spi_bus 1 // set sdcard_spi_bus = 2
// set flash_spi_bus = 2
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
imu_align CW270 // set gyro_1_sensor_align = CW270
// set gyro_1_align_yaw = 2700
// set i2c1_pullup = ON
)""; //end of madflight_board


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F405 (S405) 4.3.1 Jul 13 2022 / 03:32:11 (8d4f005) MSP API: 1.44

#define USE_GYRO
#define USE_GYRO_SPI_MPU9250
#define USE_ACC
#define USE_ACC_SPI_MPU9250
#define USE_GYRO_SPI_MPU6500
#define USE_ACC_SPI_MPU6500
#define USE_MAG
#define USE_MAG_SPI_AK8963
#define USE_MAX7456
#define USE_SDCARD

board_name ALIENFLIGHTF4
manufacturer_id AFNG

# resources
resource BEEPER 1 C13
resource MOTOR 1 B08
resource MOTOR 2 B09
resource MOTOR 3 A00
resource MOTOR 4 A01
resource MOTOR 5 C06
resource MOTOR 6 C07
resource MOTOR 7 C08
resource MOTOR 8 C09
resource PPM 1 A08
resource PWM 1 A08
resource PWM 2 B00
resource PWM 3 B01
resource PWM 4 B14
resource PWM 5 B15
resource LED_STRIP 1 B15
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 4 C10
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 4 C11
resource INVERTER 2 C15
resource I2C_SCL 1 B06
resource I2C_SDA 1 B07
resource LED 1 C12
resource LED 2 D02
resource RX_BIND 1 B02
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 B03
resource SPI_MISO 1 A06
resource SPI_MISO 2 C02
resource SPI_MISO 3 B04
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 C03
resource SPI_MOSI 3 B05
resource ESCSERIAL 1 A08
resource ADC_BATT 1 C00
resource ADC_RSSI 1 C04
resource ADC_CURR 1 C01
resource ADC_EXT 1 C05
resource SDCARD_CS 1 B10
resource SDCARD_DETECT 1 B11
resource FLASH_CS 1 B12
resource GYRO_EXTI 1 C14
resource GYRO_CS 1 A04

# timer
timer A08 AF1
# pin A08: TIM1 CH1 (AF1)
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer B14 AF1
# pin B14: TIM1 CH2N (AF1)
timer B15 AF1
# pin B15: TIM1 CH3N (AF1)
timer B08 AF2
# pin B08: TIM4 CH3 (AF2)
timer B09 AF2
# pin B09: TIM4 CH4 (AF2)
timer A00 AF2
# pin A00: TIM5 CH1 (AF2)
timer A01 AF2
# pin A01: TIM5 CH2 (AF2)
timer C06 AF3
# pin C06: TIM8 CH1 (AF3)
timer C07 AF3
# pin C07: TIM8 CH2 (AF3)
timer C08 AF3
# pin C08: TIM8 CH3 (AF3)
timer C09 AF3
# pin C09: TIM8 CH4 (AF3)

# dma
dma SPI_TX 2 0
# SPI_TX 2: DMA1 Stream 4 Channel 0
dma ADC 1 0
# ADC 1: DMA2 Stream 0 Channel 0
dma pin A08 1
# pin A08: DMA2 Stream 1 Channel 6
dma pin B00 0
# pin B00: DMA1 Stream 7 Channel 5
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin B14 1
# pin B14: DMA2 Stream 2 Channel 6
dma pin B15 0
# pin B15: DMA2 Stream 6 Channel 0
dma pin B08 0
# pin B08: DMA1 Stream 7 Channel 2
dma pin A00 0
# pin A00: DMA1 Stream 2 Channel 6
dma pin A01 0
# pin A01: DMA1 Stream 4 Channel 6
dma pin C06 0
# pin C06: DMA2 Stream 2 Channel 0
dma pin C07 0
# pin C07: DMA2 Stream 2 Channel 0
dma pin C08 1
# pin C08: DMA2 Stream 4 Channel 7
dma pin C09 0
# pin C09: DMA2 Stream 7 Channel 7

# feature
feature RX_SERIAL
feature MOTOR_STOP

# map
map TAER1234

# serial
serial 1 64 115200 57600 0 115200

# master
set align_mag = CW180FLIP
set mag_align_pitch = 1800
set mag_align_yaw = 1800
set mag_bustype = I2C
set mag_i2c_device = 1
set baro_bustype = I2C
set baro_i2c_device = 1
set serialrx_provider = SPEK2048
set spektrum_sat_bind = 9
set blackbox_device = SDCARD
set dshot_burst = ON
set battery_meter = ADC
set beeper_inversion = ON
set beeper_od = OFF
set sdcard_detect_inverted = ON
set sdcard_mode = SPI
set sdcard_spi_bus = 2
set flash_spi_bus = 2
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW270
set gyro_1_align_yaw = 2700
set i2c1_pullup = ON

*/
