import re
import os
import datetime 

source_dirname = "src"

ignore_defines = ["USE_GYRO", "USE_ACC.*", "USE_MAG", "USE_BARO", "USE_FLASH"]

def convert(infile, outfile) :
    #read lines from infile
    f = open(infile,"r")
    lines = f.readlines()
    f.close()

    #parse lines to topics
    defines = []
    board_name = ""
    manufacturer_id = ""
    resources = {}
    sets = {}
    motors = []
    for line in lines:
        s = line.strip();
        s = re.sub(" +", " ", s) #replace multiple spaces with one space
        s = s + "   " #add dummy spaces to fill at least p[4]
        p = s.split(" ")
        if p[0] == "#define" :
            found = False;
            for ignore in ignore_defines :
                if re.fullmatch(ignore, p[1]) : 
                    found = True
                    break
            if not found : defines.append( p[1].replace("_GYRO_","_IMU_") )
        if p[0] == "board_name" :
            board_name = p[1]
        if p[0] == "manufacturer_id" :
            manufacturer_id = p[1]
        if p[0] == "resource" :
            pin = "P" + re.sub(r"0([0-9])", r"\1", p[3])
            if p[1] == "MOTOR" :
                motors.append( pin )
            else :
                resources[ p[1] + ":" + p[2]] = pin
        if p[0] == "set" :
            sets[ p[1]] = p[3]

    #debug print topics
    # print( "defines:", defines )
    # print( "board_name:", board_name )
    # print( "manufacturer_id:", manufacturer_id )
    # print( "resources:", resources )
    # print( "sets:", sets )
    # print( "motors:", motors )

    #output madflight target header file
    f = open(outfile,"w")

    def fprint(txt) :
        f.write(txt + "\n")

    fprint( "/*==============================================================================" )
    fprint( "Generated on: " + str(datetime.datetime.now()) )
    fprint( "Generated by: _convert.py in this directory" )
    fprint( "Source: https://github.com/betaflight/unified-targets" )
    fprint( "Board name: " + board_name )
    fprint( "Manufacturer ID: " + manufacturer_id )
    fprint( "" )
    fprint( "//copy this line to hw_STM32.h to use this flight controller, or copy/paste this file into hw_STM32.h" )
    fprint( "#include \"betaflight-targets/" + outfile + "\"" )
    fprint( "==============================================================================*/" )

    for define in defines:
        fprint( "#define " + define )

    fprint( "" )
    fprint( "//LED:" )
    fprint( "const int HW_PIN_LED      = " + resources.get("LED:1","-1") + ";" )
    fprint( "#define LED_ON 0 //low = on" )

    fprint( "" )
    fprint( "//Battery voltage divider:" )
    fprint( "const int HW_PIN_BAT_ADC  = " + resources.get("ADC_BATT:1","-1") + ";" )
    fprint( "const int HW_PIN_BAT_CURR = " + resources.get("ADC_CURR:1","-1") + ";" )

    fprint( "" )
    fprint( "//GPS: (SERIAL1)" )
    fprint( "const int HW_PIN_GPS_RX   = " + resources.get("SERIAL_RX:1","-1") + ";" )
    fprint( "const int HW_PIN_GPS_TX   = " + resources.get("SERIAL_TX:1","-1") + ";" )
#    fprint( "HardwareSerial gps_Serial(HW_PIN_GPS_RX, HW_PIN_GPS_TX);" )

    fprint( "" )
    fprint( "//RC Receiver: (SERIAL3)" )
    fprint( "const int HW_PIN_RCIN_RX  = " + resources.get("SERIAL_RX:3","-1") + ";" )
    fprint( "const int HW_PIN_RCIN_TX  = " + resources.get("SERIAL_TX:3","-1") + ";" )
#    fprint( "HardwareSerial *rcin_Serial = new HardwareSerial(HW_PIN_RCIN_RX, HW_PIN_RCIN_TX);" )

    fprint( "" )
    fprint( "//IMU:" )
    fprint( "const int HW_PIN_IMU_INT  = " + resources.get("GYRO_EXTI:1","-1") + ";" )

    i2c = sets.get("mag_i2c_device")
    i2c = sets.get("baro_i2c_device",i2c)
    if i2c is None: i2c = "1"
    fprint( "" )
    fprint( "//I2C: (I2C"+i2c+")" )
    fprint( "const int HW_PIN_I2C_SDA  = " + resources.get("I2C_SCL:" + i2c,"-1") + ";" )
    fprint( "const int HW_PIN_I2C_SCL  = " + resources.get("I2C_SDA:" + i2c,"-1") + ";" )
    fprint( "typedef TwoWire HW_WIRETYPE; //define the class to use for I2C" )
#    fprint( "HW_WIRETYPE *i2c = &Wire; //&Wire or &Wire1" )

    spi = sets.get("gyro_1_spibus","1")
    fprint( "" )
    fprint( "//SPI: (SPI"+spi+")" )
    fprint( "const int HW_PIN_SPI_MISO = " + resources.get("SPI_MISO:" + spi,"-1") + ";" )
    fprint( "const int HW_PIN_SPI_CS   = " + resources.get("GYRO_CS:1","-1") + ";" )
    fprint( "const int HW_PIN_SPI_SCLK = " + resources.get("SPI_SCK:" + spi,"-1") + ";" )
    fprint( "const int HW_PIN_SPI_MOSI = " + resources.get("SPI_MOSI:" + spi,"-1") + ";" )
#    fprint( "SPIClass *spi = &SPI;" )

    fprint( "" )
    fprint( "//Outputs:" )
    fprint( "#define HW_OUT_COUNT "+str(len(motors)) )
    fprint( "const int16_t HW_PIN_OUT[HW_OUT_COUNT] = {" + ",".join(motors) + "};" )


    fprint( "" )
    fprint( "" )
    fprint( "/*" )
    fprint( "#==============================================================================" )
    fprint( "# BetaFlight Source file" )
    fprint( "#==============================================================================" )
    fprint( "".join(lines) )
    fprint( "*/" )

    f.close()


for filename in os.listdir(source_dirname) :
    if filename != "readme.md" :
        convert(source_dirname + "/" + filename, filename + ".h")