/*==============================================================================
Generated on: 2023-12-28 01:59:36.573755
Generated by: _convert.py in this directory
Source: https://github.com/betaflight/unified-targets
Board name: WORMFC
Manufacturer ID: FOSS

//copy this line to hw_STM32.h to use this flight controller, or copy/paste this file into hw_STM32.h
#include "betaflight-targets/FOSS-WORMFC.config.h"
==============================================================================*/
#define USE_IMU_SPI_MPU6500
#define USE_BARO_SPI_LPS
#define USE_MAX7456

//LED:
const int HW_PIN_LED      = PA15;
#define LED_ON 0 //low = on

//Battery voltage divider:
const int HW_PIN_BAT_ADC  = PC1;
const int HW_PIN_BAT_CURR = PC2;

//GPS: (SERIAL1)
const int HW_PIN_GPS_RX   = PB7;
const int HW_PIN_GPS_TX   = PB6;

//RC Receiver: (SERIAL3)
const int HW_PIN_RCIN_RX  = PB11;
const int HW_PIN_RCIN_TX  = PB10;

//IMU:
const int HW_PIN_IMU_INT  = -1;

//I2C: (I2C1)
const int HW_PIN_I2C_SDA  = -1;
const int HW_PIN_I2C_SCL  = -1;
typedef TwoWire HW_WIRETYPE; //define the class to use for I2C

//SPI: (SPI1)
const int HW_PIN_SPI_MISO = PA6;
const int HW_PIN_SPI_CS   = PA4;
const int HW_PIN_SPI_SCLK = PA5;
const int HW_PIN_SPI_MOSI = PA7;

//Outputs:
#define HW_OUT_COUNT 6
const int16_t HW_PIN_OUT[HW_OUT_COUNT] = {PB1,PB0,PA2,PA3,PA10,PA8};


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F405 (S405) 4.2.0 Feb  2 2020 / 16:57:58 (norevision) MSP API: 1.43

#define USE_GYRO
#define USE_GYRO_SPI_MPU6500
#define USE_ACC
#define USE_ACC_SPI_MPU6500
#define USE_BARO
#define USE_BARO_SPI_LPS
#define USE_MAX7456

board_name WORMFC
manufacturer_id FOSS

# resources
resource BEEPER 1 B14
resource MOTOR 1 B01
resource MOTOR 2 B00
resource MOTOR 3 A02
resource MOTOR 4 A03
resource MOTOR 5 A10
resource MOTOR 6 A08
resource PPM 1 B09
resource LED_STRIP 1 A10
resource SERIAL_TX 1 B06
resource SERIAL_TX 3 B10
resource SERIAL_TX 4 A00
resource SERIAL_TX 6 C06
resource SERIAL_RX 1 B07
resource SERIAL_RX 3 B11
resource SERIAL_RX 4 A01
resource SERIAL_RX 6 C07
resource INVERTER 3 B12
resource INVERTER 6 B13
resource LED 1 A15
resource LED 2 C14
resource SPI_SCK 1 A05
resource SPI_SCK 3 B03
resource SPI_MISO 1 A06
resource SPI_MISO 3 B04
resource SPI_MOSI 1 A07
resource SPI_MOSI 3 B05
resource ESCSERIAL 1 B09
resource ADC_BATT 1 C01
resource ADC_CURR 1 C02
resource BARO_CS 1 B08
resource SDCARD_DETECT 1 B15
resource OSD_CS 1 C00
resource GYRO_CS 1 A04
resource USB_DETECT 1 A09

# timer
timer B09 AF2
# pin B09: TIM4 CH4 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer A02 AF1
# pin A02: TIM2 CH3 (AF1)
timer A03 AF1
# pin A03: TIM2 CH4 (AF1)
timer A10 AF1
# pin A10: TIM1 CH3 (AF1)
timer A08 AF1
# pin A08: TIM1 CH1 (AF1)

# dma
dma ADC 1 1
# ADC 1: DMA2 Stream 4 Channel 0
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin B00 0
# pin B00: DMA1 Stream 7 Channel 5
dma pin A02 0
# pin A02: DMA1 Stream 1 Channel 3
dma pin A03 1
# pin A03: DMA1 Stream 6 Channel 3
dma pin A10 1
# pin A10: DMA2 Stream 6 Channel 6
dma pin A08 1
# pin A08: DMA2 Stream 1 Channel 6

# feature
feature OSD

# master
set baro_spi_device = 3
set blackbox_device = SDCARD
set dshot_burst = ON
set current_meter = ADC
set battery_meter = ADC
set beeper_inversion = ON
set beeper_od = OFF
set system_hse_mhz = 8
set max7456_spi_bus = 3
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW180FLIP
set gyro_1_align_pitch = 1800
set gyro_1_align_yaw = 1800

*/
