"""
madflight parameter documentation generator script for platformio.
(c) 2026 madflight
"""

from os.path import join
import glob
import sys
import re
Import("env")

# Install yaml if missing
try:
    import yaml
except ImportError:
    env.Execute("$PYTHONEXE -m pip install pyyaml")
    import yaml

platform = env.PioPlatform()
PROJ_SRC = env["PROJECT_SRC_DIR"]
PROJECT_DIR = env["PROJECT_DIR"]
CONFIG_FILES = glob.glob(join(PROJ_SRC, '*/param.yaml'), recursive=True)
outfilename =  PROJECT_DIR + "/Parameters.md"

print("==============================================")
print("madflight documentation generator")
print(f"Generating {outfilename}")

#load all config files into module,param
module = {}
param = {}
for filename in CONFIG_FILES:
  print(f"  from {filename.removeprefix(PROJ_SRC)}")
  with open(filename) as stream:
    y = yaml.safe_load(stream)
    #add modules with fields: title, comment
    for k in y['module']:
      module[k] = y['module'][k]
      #create title if not exist 
      if not 'title' in module[k]:
        module[k]['title'] = ""
      #create comment if not exist 
      if not 'comment' in module[k]:
        module[k]['comment'] = ""

    #add parameters with fields: comment, since, options, default
    since = ""
    for k in y['param']:
      #add param
      param[k] = y['param'][k]
      #create comment if not exist 
      if not 'comment' in param[k]:
        param[k]['comment'] = ""
      #create since if not exist 
      if 'since' in param[k]:
        since = param[k]['since']
      param[k]['since'] = since
      #create options if not exist 
      if not 'options' in param[k]:
        param[k]['options'] = {}
      #create default if not exist 
      if not 'default' in param[k]:
        param[k]['default'] = ""

#update version
fn = PROJECT_DIR + "/library.properties"
s = ""
with open(fn, "r") as f:
  s = f.read()
if(s):
  s2 = re.sub("version=.*", "version="+y['version'], s) # note: '.' does not match newline
  with open(fn, "w") as f:
    f.write(s2)

#update version
fn = PROJECT_DIR + "/src/madflight_modules.h"
s = ""
with open(fn, "r") as f:
  s = f.read()
if(s):  
  s2 = re.sub("#define MADFLIGHT_VERSION.*", '#define MADFLIGHT_VERSION "madflight v' + y['version'] + '"', s) # note: '.' does not match newline
  with open(fn, "w") as f:
    f.write(s2)

#write Parameters.md doc file
param = dict(sorted(param.items()))
with open(outfilename, "w") as f:
  f.write(f"<!--- DO NOT EDIT - GENERATED BY extras/scripts/doc_generator.py -->\n")
  f.write("\n")  

  f.write(y['pageheader'].replace("%VERSION%", y['version']));

  #modules overview
  f.write("\n") 
  f.write(f"## Modules\n")
  f.write("\n") 
  for mod in y['module']:
    f.write(f" - [{mod.upper()} - {module[mod]['title']}](#{mod.lower()})\n")

  mod = ""
  for k in param:
    p = param[k]

    #module header
    if(mod != k[0:3]):
      mod = k[0:3]
      f.write(f"\n")
      f.write(f"## <a id=\"{mod.lower()}\"></a>{mod.upper()} - {module[mod]['title']}\n")
      f.write(f"{module[mod]['comment']}\n")
      f.write(f"\n")
      f.write(f"|Parameter|Description|Default|Options|\n")
      f.write(f"|-|-|-|-|\n")

    #parameter row
    options = "<br>".join(p['options'])

    descr = p['comment']
    if p['since']:
      descr += f"<br>_since {p['since']}_"

    f.write(f"|`{k}`|{descr}|{p['default']}|{options}|\n")


print("==============================================")
