/*==============================================================================
Generated on: 2025-04-16 00:58:15.085133
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: NOX
Manufacturer ID: AIRB

//copy this line to madflight.ino to use this flight controller
#include <madflight_zzz_AIRB-NOX.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out, or use madflight_config to override.
==============================================================================*/

#define MF_BOARD_NAME "BETAFLIGHT-AIRB-NOX"
#define MF_MCU_NAME "STM32F411"

const char* madflight_board = R""(
imu_bus_type SPI
imu_gizmo MPU6000 // #define USE_GYRO_SPI_MPU6000
imu_gizmo MPU6500 // #define USE_GYRO_SPI_MPU6500
bar_gizmo SPI_BMP280 // #define USE_BARO_SPI_BMP280
// resource BEEPER 1 C13
pin_out0 PA1 // resource MOTOR 1 A01
pin_out1 PA7 // resource MOTOR 2 A07
pin_out2 PB8 // resource MOTOR 3 B08
pin_out3 PB1 // resource MOTOR 4 B01
pin_rcl_ppm PB10 // resource PPM 1 B10
// resource LED_STRIP 1 A00
pin_ser0_tx PB6 // resource SERIAL_TX 1 B06
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser0_rx PB7 // resource SERIAL_RX 1 B07
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_ser1_inv PC14 // resource INVERTER 2 C14
pin_led PA4 // resource LED 1 A04
pin_spi0_sclk PB3 // resource SPI_SCK 1 B03
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi0_miso PB4 // resource SPI_MISO 1 B04
pin_spi1_miso PB14 // resource SPI_MISO 2 B14
pin_spi0_mosi PB5 // resource SPI_MOSI 1 B05
pin_spi1_mosi PB15 // resource SPI_MOSI 2 B15
// resource ESCSERIAL 1 B10
pin_bat_v PA5 // resource ADC_BATT 1 A05
bat_gizmo ADC
// resource BARO_CS 1 A09
// resource FLASH_CS 1 A15
// resource OSD_CS 1 A10
pin_imu_int PNONE // resource GYRO_EXTI 1 NONE
pin_imu_cs PB12 // resource GYRO_CS 1 B12
// set baro_spi_device = 2
// set serialrx_provider = SBUS
// set blackbox_device = SPIFLASH
// set min_throttle = 1070
// set use_unsynced_pwm = OFF
// set motor_pwm_protocol = ONESHOT125
// set motor_pwm_rate = 480
// set current_meter = ESC
// set battery_meter = ESC
// set beeper_inversion = ON
// set beeper_od = OFF
// set system_hse_mhz = 8
// set max7456_spi_bus = 2
// set flash_spi_bus = 1
// set gyro_1_bustype = SPI
imu_spi_bus 1 // set gyro_1_spibus = 2
)""; //end of madflight_board


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F411 (S411) 4.1.0 Oct 16 2019 / 11:57:34 (c37a7c91a) MSP API: 1.42

#define USE_GYRO
#define USE_GYRO_SPI_MPU6000
#define USE_GYRO_SPI_MPU6500
#define USE_ACC
#define USE_ACC_SPI_MPU6000
#define USE_ACC_SPI_MPU6500
#define USE_BARO
#define USE_BARO_SPI_BMP280
#define USE_FLASH
#define USE_FLASH_M25P16
#define USE_MAX7456

board_name NOX
manufacturer_id AIRB

# resources
resource BEEPER 1 C13
resource MOTOR 1 A01
resource MOTOR 2 A07
resource MOTOR 3 B08
resource MOTOR 4 B01
resource PPM 1 B10
resource LED_STRIP 1 A00
resource SERIAL_TX 1 B06
resource SERIAL_TX 2 A02
resource SERIAL_RX 1 B07
resource SERIAL_RX 2 A03
resource INVERTER 2 C14
resource LED 1 A04
resource SPI_SCK 1 B03
resource SPI_SCK 2 B13
resource SPI_MISO 1 B04
resource SPI_MISO 2 B14
resource SPI_MOSI 1 B05
resource SPI_MOSI 2 B15
resource ESCSERIAL 1 B10
resource ADC_BATT 1 A05
resource BARO_CS 1 A09
resource FLASH_CS 1 A15
resource OSD_CS 1 A10
# Disabling GYRO_EXTI since gyro and OSD are on same SPI bus
# resource GYRO_EXTI 1 A08
resource GYRO_EXTI 1 NONE
resource GYRO_CS 1 B12

# timer
timer B10 AF1
# pin B10: TIM2 CH3 (AF1)
timer A01 AF2
# pin A01: TIM5 CH2 (AF2)
timer A07 AF1
# pin A07: TIM1 CH1N (AF1)
timer B08 AF2
# pin B08: TIM4 CH3 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer A00 AF1
# pin A00: TIM2 CH1 (AF1)
timer A02 AF3
# pin A02: TIM9 CH1 (AF3)
timer A03 AF3
# pin A03: TIM9 CH2 (AF3)

# dma
dma ADC 1 1
# ADC 1: DMA2 Stream 4 Channel 0
dma pin B10 0
# pin B10: DMA1 Stream 1 Channel 3
dma pin A01 0
# pin A01: DMA1 Stream 4 Channel 6
dma pin A07 0
# pin A07: DMA2 Stream 6 Channel 0
dma pin B08 0
# pin B08: DMA1 Stream 7 Channel 2
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin A00 0
# pin A00: DMA1 Stream 5 Channel 3

# feature
feature RX_SERIAL
feature OSD
feature SOFTSERIAL
feature ESC_SENSOR

# serial
serial 0 2048 115200 57600 0 115200
serial 1 64 115200 57600 0 115200

# master
set baro_spi_device = 2
set serialrx_provider = SBUS
set blackbox_device = SPIFLASH
set min_throttle = 1070
set use_unsynced_pwm = OFF
set motor_pwm_protocol = ONESHOT125
set motor_pwm_rate = 480
set current_meter = ESC
set battery_meter = ESC
set beeper_inversion = ON
set beeper_od = OFF
set system_hse_mhz = 8
set max7456_spi_bus = 2
set flash_spi_bus = 1
set gyro_1_bustype = SPI
set gyro_1_spibus = 2

*/
