/*==============================================================================
Generated on: 2025-03-18 18:40:43.321170
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: MAMBAF722
Manufacturer ID: DIAT

//copy this line to madflight.ino to use this flight controller
#include <madflight_board_DIAT-MAMBAF722.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-DIAT-MAMBAF722"
#define HAL_MCU "STM32F7X2"

#define MADFLIGHT_BOARD R""(
imu_gizmo MPU6000 // #define USE_GYRO_SPI_MPU6000
pin_led PC15 // resource LED 1 C15
// resource LED 2 C14
// resource BEEPER 1 B02
// set beeper_inversion = ON
// set beeper_od = OFF
pin_imu_int PC4 // resource GYRO_EXTI 1 C04
pin_imu_cs PA4 // resource GYRO_CS 1 A04
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
imu_align CW180 // set gyro_1_sensor_align = CW180
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi1_miso PB14 // resource SPI_MISO 2 B14
pin_spi1_mosi PB15 // resource SPI_MOSI 2 B15
pin_spi2_sclk PC10 // resource SPI_SCK 3 C10
pin_spi2_miso PC11 // resource SPI_MISO 3 C11
pin_spi2_mosi PB5 // resource SPI_MOSI 3 B05
// resource FLASH_CS 1 A15
// set flash_spi_bus = 3
// resource OSD_CS 1 B12
// set max7456_spi_bus = 2
pin_bat_v PC1 // resource ADC_BATT 1 C01
bat_gizmo ADC
// resource ADC_RSSI 1 C02
pin_bat_i PC3 // resource ADC_CURR 1 C03
bat_gizmo ADC
// set adc_device = 3
pin_ser0_tx PB6 // resource SERIAL_TX 1 B06
pin_ser0_rx PB7 // resource SERIAL_RX 1 B07
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_ser2_tx PB10 // resource SERIAL_TX 3 B10
pin_ser2_rx PB11 // resource SERIAL_RX 3 B11
pin_ser3_tx PA0 // resource SERIAL_TX 4 A00
pin_ser3_rx PA1 // resource SERIAL_RX 4 A01
pin_ser4_tx PC12 // resource SERIAL_TX 5 C12
pin_ser4_rx PD2 // resource SERIAL_RX 5 D02
pin_ser5_tx PC6 // resource SERIAL_TX 6 C06
pin_ser5_rx PC7 // resource SERIAL_RX 6 C07
pin_out0 PC8 // resource MOTOR 1 C08
pin_out1 PC9 // resource MOTOR 2 C09
pin_out2 PA8 // resource MOTOR 3 A08
pin_out3 PA9 // resource MOTOR 4 A09
pin_rcl_ppm PB9 // resource PPM 1 B09
// resource LED_STRIP 1 B03
// resource CAMERA_CONTROL 1 B08
// resource PINIO 1 B00
// set baro_bustype = I2C
bar_i2c_bus 0 // set baro_i2c_device = 1
mag_i2c_bus 0 // set mag_i2c_device = 1
// set mag_bustype = I2C
// set serialrx_provider = SBUS
// set blackbox_device = SPIFLASH
// set dshot_burst = ON
// set motor_pwm_protocol = DSHOT600
// set pinio_box = 0,255,255,255
// set pinio_config = 129,1,1,1
// set current_meter = ADC
// set battery_meter = ADC
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F7X2 (S7X2) 4.0.1 May  1 2019 / 22:19:19 (25f4a5ffe) MSP API: 1.41

#define USE_ACC
#define USE_ACC_SPI_MPU6000
#define USE_GYRO
#define USE_GYRO_SPI_MPU6000
#define USE_FLASH
#define USE_FLASH_W25Q128FV
#define USE_MAX7456

board_name MAMBAF722
manufacturer_id DIAT

# I/O
resource LED 1 C15
resource LED 2 C14
resource BEEPER 1 B02
set beeper_inversion = ON
set beeper_od = OFF

# ACC/GYRO
resource GYRO_EXTI 1 C04
resource GYRO_CS 1 A04
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW180

# SPI
resource SPI_SCK 1 A05
resource SPI_MISO 1 A06
resource SPI_MOSI 1 A07

resource SPI_SCK 2 B13
resource SPI_MISO 2 B14
resource SPI_MOSI 2 B15

resource SPI_SCK 3 C10
resource SPI_MISO 3 C11
resource SPI_MOSI 3 B05

# FLASH
resource FLASH_CS 1 A15
set flash_spi_bus = 3

# OSD
resource OSD_CS 1 B12
set max7456_spi_bus = 2

# ADC
resource ADC_BATT 1 C01
resource ADC_RSSI 1 C02
resource ADC_CURR 1 C03
set adc_device = 3

# SERIAL PORTS
resource SERIAL_TX 1 B06
resource SERIAL_RX 1 B07

resource SERIAL_TX 2 A02
resource SERIAL_RX 2 A03

resource SERIAL_TX 3 B10
resource SERIAL_RX 3 B11

resource SERIAL_TX 4 A00
resource SERIAL_RX 4 A01

resource SERIAL_TX 5 C12
resource SERIAL_RX 5 D02

resource SERIAL_TX 6 C06
resource SERIAL_RX 6 C07

# TIMERS
timer B09 AF3
# pin B09: TIM11 CH1 (AF3)
timer C08 AF3
# pin C08: TIM8 CH3 (AF3)
timer C09 AF3
# pin C09: TIM8 CH4 (AF3)
timer A08 AF1
# pin A08: TIM1 CH1 (AF1)
timer A09 AF1
# pin A09: TIM1 CH2 (AF1)
timer B08 AF2
# pin B08: TIM4 CH3 (AF2)
timer B03 AF1
# pin B03: TIM2 CH2 (AF1)
resource MOTOR 1 C08
resource MOTOR 2 C09
resource MOTOR 3 A08
resource MOTOR 4 A09
resource PPM 1 B09
resource LED_STRIP 1 B03
resource CAMERA_CONTROL 1 B08

# dma
dma ADC 3 0
# ADC 3: DMA2 Stream 0 Channel 2
dma pin C08 0
# pin C08: DMA2 Stream 2 Channel 0
dma pin C09 0
# pin C09: DMA2 Stream 7 Channel 7
dma pin A08 0
# pin A08: DMA2 Stream 6 Channel 0
dma pin A09 0
# pin A09: DMA2 Stream 6 Channel 0
dma pin B08 0
# pin B08: DMA1 Stream 7 Channel 2
dma pin B03 0
# pin B03: DMA1 Stream 6 Channel 3

# serial
serial 0 64 115200 57600 0 115200
serial 3 1 19200 57600 0 115200

# EXTRAS
resource PINIO 1 B00

# feature
feature RX_SERIAL
feature TELEMETRY
feature SOFTSERIAL
feature OSD

# master
set baro_bustype = I2C
set baro_i2c_device = 1
set mag_i2c_device = 1
set mag_bustype = I2C
set serialrx_provider = SBUS
set blackbox_device = SPIFLASH
set dshot_burst = ON
set motor_pwm_protocol = DSHOT600
set pinio_box = 0,255,255,255
set pinio_config = 129,1,1,1
set current_meter = ADC
set battery_meter = ADC

*/
