/*==============================================================================
Generated on: 2025-03-24 13:58:26.397756
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: IFLIGHT_BLITZ_F7_AIO
Manufacturer ID: IFRC

//copy this line to madflight.ino to use this flight controller
#include <madflight_zzz_IFRC-IFLIGHT_BLITZ_F7_AIO.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-IFRC-IFLIGHT_BLITZ_F7_AIO"
#define HAL_MCU "STM32F745"

#define MADFLIGHT_BOARD R""(
imu_gizmo ICM42688P // #define USE_GYRO_SPI_ICM42688P
bar_gizmo DPS310 // #define USE_BARO_DPS310
// resource BEEPER 1 D03
pin_out0 PB4 // resource MOTOR 1 B04
pin_out1 PB0 // resource MOTOR 2 B00
pin_out2 PB5 // resource MOTOR 3 B05
pin_out3 PB1 // resource MOTOR 4 B01
pin_out4 PE9 // resource MOTOR 5 E09
pin_out5 PE11 // resource MOTOR 6 E11
pin_out6 PE13 // resource MOTOR 7 E13
pin_out7 PE14 // resource MOTOR 8 E14
// resource SERVO 1 B06
// resource SERVO 2 B07
pin_rcl_ppm PB3 // resource PPM 1 B03
// resource LED_STRIP 1 C09
pin_ser0_tx PA9 // resource SERIAL_TX 1 A09
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser2_tx PB10 // resource SERIAL_TX 3 B10
pin_ser3_tx PA0 // resource SERIAL_TX 4 A00
pin_ser4_tx PC12 // resource SERIAL_TX 5 C12
pin_ser5_tx PC6 // resource SERIAL_TX 6 C06
pin_ser6_tx PE8 // resource SERIAL_TX 7 E08
pin_ser7_tx PE1 // resource SERIAL_TX 8 E01
pin_ser0_rx PA10 // resource SERIAL_RX 1 A10
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_ser2_rx PB11 // resource SERIAL_RX 3 B11
pin_ser3_rx PA1 // resource SERIAL_RX 4 A01
pin_ser4_rx PD2 // resource SERIAL_RX 5 D02
pin_ser5_rx PC7 // resource SERIAL_RX 6 C07
pin_ser6_rx PE7 // resource SERIAL_RX 7 E07
pin_ser7_rx PE0 // resource SERIAL_RX 8 E00
pin_i2c0_scl PB8 // resource I2C_SCL 1 B08
pin_i2c3_scl PD12 // resource I2C_SCL 4 D12
pin_i2c0_sda PB9 // resource I2C_SDA 1 B09
pin_i2c3_sda PD13 // resource I2C_SDA 4 D13
pin_led PD15 // resource LED 1 D15
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi2_sclk PC10 // resource SPI_SCK 3 C10
pin_spi3_sclk PE2 // resource SPI_SCK 4 E02
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi1_miso PB14 // resource SPI_MISO 2 B14
pin_spi2_miso PC11 // resource SPI_MISO 3 C11
pin_spi3_miso PE5 // resource SPI_MISO 4 E05
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi1_mosi PB15 // resource SPI_MOSI 2 B15
pin_spi2_mosi PD6 // resource SPI_MOSI 3 D06
pin_spi3_mosi PE6 // resource SPI_MOSI 4 E06
// resource CAMERA_CONTROL 1 B03
pin_bat_v PC3 // resource ADC_BATT 1 C03
bat_gizmo ADC
// resource ADC_RSSI 1 C05
pin_bat_i PC2 // resource ADC_CURR 1 C02
bat_gizmo ADC
// resource ADC_EXT 1 C01
// resource FLASH_CS 1 A15
// resource OSD_CS 1 E04
pin_imu_int PD0 // resource GYRO_EXTI 1 D00
pin_imu_cs PA4 // resource GYRO_CS 1 A04
// set mag_bustype = I2C
mag_i2c_bus 0 // set mag_i2c_device = 1
// set baro_bustype = I2C
bar_i2c_bus 3 // set baro_i2c_device = 4
// set blackbox_device = SPIFLASH
// set align_board_yaw = 135
// set current_meter = ADC
// set battery_meter = ADC
// set ibata_scale = 200
// set beeper_inversion = ON
// set beeper_od = OFF
// set max7456_spi_bus = 4
// set dashboard_i2c_bus = 1
// set flash_spi_bus = 3
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F745 (S745) 4.3.1 Jul 13 2022 / 03:35:21 (8d4f005) MSP API: 1.44

#define USE_ACCGYRO_BMI270
#define USE_GYRO
#define USE_GYRO_SPI_ICM42688P
#define USE_ACC
#define USE_ACC_SPI_ICM42688P
#define USE_BARO
#define USE_BARO_DPS310
#define USE_FLASH
#define USE_FLASH_M25P16
#define USE_MAX7456

board_name IFLIGHT_BLITZ_F7_AIO
manufacturer_id IFRC

# resources
resource BEEPER 1 D03
resource MOTOR 1 B04
resource MOTOR 2 B00
resource MOTOR 3 B05
resource MOTOR 4 B01
resource MOTOR 5 E09
resource MOTOR 6 E11
resource MOTOR 7 E13
resource MOTOR 8 E14
resource SERVO 1 B06
resource SERVO 2 B07
resource PPM 1 B03
resource LED_STRIP 1 C09
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 3 B10
resource SERIAL_TX 4 A00
resource SERIAL_TX 5 C12
resource SERIAL_TX 6 C06
resource SERIAL_TX 7 E08
resource SERIAL_TX 8 E01
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource SERIAL_RX 3 B11
resource SERIAL_RX 4 A01
resource SERIAL_RX 5 D02
resource SERIAL_RX 6 C07
resource SERIAL_RX 7 E07
resource SERIAL_RX 8 E00
resource I2C_SCL 1 B08
resource I2C_SCL 4 D12
resource I2C_SDA 1 B09
resource I2C_SDA 4 D13
resource LED 1 D15
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 C10
resource SPI_SCK 4 E02
resource SPI_MISO 1 A06
resource SPI_MISO 2 B14
resource SPI_MISO 3 C11
resource SPI_MISO 4 E05
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 B15
resource SPI_MOSI 3 D06
resource SPI_MOSI 4 E06
resource CAMERA_CONTROL 1 B03
resource ADC_BATT 1 C03
resource ADC_RSSI 1 C05
resource ADC_CURR 1 C02
resource ADC_EXT 1 C01
resource FLASH_CS 1 A15
resource OSD_CS 1 E04
resource GYRO_EXTI 1 D00
resource GYRO_CS 1 A04

# timer
timer B03 AF1
# pin B03: TIM2 CH2 (AF1)
timer B04 AF2
# pin B04: TIM3 CH1 (AF2)
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer B05 AF2
# pin B05: TIM3 CH2 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer E09 AF1
# pin E09: TIM1 CH1 (AF1)
timer E11 AF1
# pin E11: TIM1 CH2 (AF1)
timer E13 AF1
# pin E13: TIM1 CH3 (AF1)
timer E14 AF1
# pin E14: TIM1 CH4 (AF1)
timer B06 AF2
# pin B06: TIM4 CH1 (AF2)
timer B07 AF2
# pin B07: TIM4 CH2 (AF2)
timer C09 AF3
# pin C09: TIM8 CH4 (AF3)

# dma
dma ADC 1 0
# ADC 1: DMA2 Stream 0 Channel 0
dma pin B03 0
# pin B03: DMA1 Stream 6 Channel 3
dma pin B04 0
# pin B04: DMA1 Stream 4 Channel 5
dma pin B00 0
# pin B00: DMA1 Stream 7 Channel 5
dma pin B05 0
# pin B05: DMA1 Stream 5 Channel 5
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin E09 1
# pin E09: DMA2 Stream 1 Channel 6
dma pin E11 1
# pin E11: DMA2 Stream 2 Channel 6
dma pin E13 1
# pin E13: DMA2 Stream 6 Channel 6
dma pin E14 0
# pin E14: DMA2 Stream 4 Channel 6
dma pin B06 0
# pin B06: DMA1 Stream 0 Channel 2
dma pin B07 0
# pin B07: DMA1 Stream 3 Channel 2
dma pin C09 0
# pin C09: DMA2 Stream 7 Channel 7

# feature
feature OSD

# serial
serial 2 64 115200 57600 0 115200

# master
set mag_bustype = I2C
set mag_i2c_device = 1
set baro_bustype = I2C
set baro_i2c_device = 4
set blackbox_device = SPIFLASH
set align_board_yaw = 135
set current_meter = ADC
set battery_meter = ADC
set ibata_scale = 200
set beeper_inversion = ON
set beeper_od = OFF
set max7456_spi_bus = 4
set dashboard_i2c_bus = 1
set flash_spi_bus = 3
set gyro_1_bustype = SPI
set gyro_1_spibus = 1

*/
