/*==============================================================================
Generated on: 2025-03-24 13:58:25.167755
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: NERO
Manufacturer ID: BKMN

//copy this line to madflight.ino to use this flight controller
#include <madflight_zzz_BKMN-NERO.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-BKMN-NERO"
#define HAL_MCU "STM32F7X2"

#define MADFLIGHT_BOARD R""(
imu_gizmo ICM20602 // #define USE_GYRO_SPI_ICM20602
// resource BEEPER 1 C01
// resource LED_STRIP 1 B00 # pin M5
pin_led PB6 // resource LED 1 B06
// resource LED 2 B05
// resource LED 3 B04
pin_out0 PA0 // resource MOTOR 1 A00
pin_out1 PA1 // resource MOTOR 2 A01
pin_out2 PA2 // resource MOTOR 3 A02
pin_out3 PA3 // resource MOTOR 4 A03
pin_out5 PB1 // resource MOTOR 6 B01
pin_out6 PC8 // resource MOTOR 7 C08
pin_out7 PC9 // resource MOTOR 8 C09
pin_ser0_tx PA9 // resource SERIAL_TX 1 A09
pin_ser0_rx PA10 // resource SERIAL_RX 1 A10
pin_ser2_tx PB10 // resource SERIAL_TX 3 B10
pin_ser2_rx PB11 // resource SERIAL_RX 3 B11
pin_ser5_tx PC6 // resource SERIAL_TX 6 C06
pin_ser5_rx PC7 // resource SERIAL_RX 6 C07
pin_i2c0_scl PB8 // resource I2C_SCL 1 B08
pin_i2c0_sda PB9 // resource I2C_SDA 1 B09
pin_bat_v PC3 // resource ADC_BATT 1 C03
bat_gizmo ADC
pin_bat_i PC2 // resource ADC_CURR 1 C02 # --> pin AD
bat_gizmo ADC
// resource ADC_RSSI 1 A04 # --> pin DA
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_imu_cs PC4 // resource GYRO_CS 1 C04
pin_imu_int PB2 // resource GYRO_EXTI 1 B02
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi1_miso PB14 // resource SPI_MISO 2 B14
pin_spi1_mosi PB15 // resource SPI_MOSI 2 B15
pin_spi2_sclk PC10 // resource SPI_SCK 3 C10
pin_spi2_miso PC11 // resource SPI_MISO 3 C11
pin_spi2_mosi PC12 // resource SPI_MOSI 3 C12
pin_bbx_cs PA15 // resource SDCARD_CS 1 A15
bbx_gizmo SDSPI
// resource SDCARD_DETECT 1 D02
// set dshot_burst = ON
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
imu_align CW0 // set gyro_1_sensor_align = CW0
// set blackbox_device = SDCARD
// set sdcard_mode = SPI
bbx_spi_bus 2 // set sdcard_spi_bus = 3
// set sdcard_detect_inverted = ON
// set beeper_inversion = ON
// set beeper_od = OFF
// set current_meter = ADC
// set battery_meter = ADC
// set mag_hardware = NONE
// set baro_hardware = NONE
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F7X2 (S7X2) 4.4.3 Mar 18 2024 / 20:58:20 (738127e7e) MSP API: 1.45

#define USE_ACC
#define USE_ACC_SPI_ICM20602
#define USE_GYRO
#define USE_GYRO_SPI_ICM20602
#define USE_SDCARD

board_name NERO
manufacturer_id BKMN

# resources
resource BEEPER 1 C01
resource LED_STRIP 1 B00 # pin M5
resource LED 1 B06
resource LED 2 B05
resource LED 3 B04

# Motors
resource MOTOR 1 A00
resource MOTOR 2 A01
resource MOTOR 3 A02
resource MOTOR 4 A03
# resource MOTOR 5 B00
resource MOTOR 6 B01
resource MOTOR 7 C08
resource MOTOR 8 C09

# UARTS
resource SERIAL_TX 1 A09
resource SERIAL_RX 1 A10
resource SERIAL_TX 3 B10
resource SERIAL_RX 3 B11
resource SERIAL_TX 6 C06
resource SERIAL_RX 6 C07

# I2C1
resource I2C_SCL 1 B08
resource I2C_SDA 1 B09

# ADC
resource ADC_BATT 1 C03
resource ADC_CURR 1 C02 # --> pin AD
resource ADC_RSSI 1 A04 # --> pin DA

# GYRO & ACC --> SPI1
resource SPI_SCK 1 A05
resource SPI_MISO 1 A06
resource SPI_MOSI 1 A07
resource GYRO_CS 1 C04
resource GYRO_EXTI 1 B02

# ACC_SPI --> SPI2 (CS pin B12)
resource SPI_SCK 2 B13
resource SPI_MISO 2 B14
resource SPI_MOSI 2 B15

# SDCARD --> SPI3
resource SPI_SCK 3 C10
resource SPI_MISO 3 C11
resource SPI_MOSI 3 C12
resource SDCARD_CS 1 A15
resource SDCARD_DETECT 1 D02

# timer
timer A00 AF2
# pin A00: TIM5 CH1 (AF2)
timer A01 AF2
# pin A01: TIM5 CH2 (AF2)
timer A02 AF2
# pin A02: TIM5 CH3 (AF2)
timer A03 AF2
# pin A03: TIM5 CH4 (AF2)
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer C08 AF3
# pin C08: TIM8 CH3 (AF3)
timer C09 AF3
# pin C09: TIM8 CH4 (AF3)

# dma
dma ADC 1 1
# ADC 1: DMA2 Stream 4 Channel 0
dma pin A00 0
# pin A00: DMA1 Stream 2 Channel 6
dma pin A01 0
# pin A01: DMA1 Stream 4 Channel 6
dma pin A02 0
# pin A02: DMA1 Stream 0 Channel 6
dma pin A03 0
# pin A03: DMA1 Stream 1 Channel 6
dma pin B00 0
# pin B00: DMA1 Stream 7 Channel 5
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin C08 0
# pin C08: DMA2 Stream 2 Channel 0
dma pin C09 0
# pin C09: DMA2 Stream 7 Channel 7

# master
set dshot_burst = ON
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW0
set blackbox_device = SDCARD
set sdcard_mode = SPI
set sdcard_spi_bus = 3
set sdcard_detect_inverted = ON
set beeper_inversion = ON
set beeper_od = OFF
set current_meter = ADC
set battery_meter = ADC
set mag_hardware = NONE
set baro_hardware = NONE

*/
