/*==============================================================================
Generated on: 2025-03-24 13:58:24.947453
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: AG3XF4
Manufacturer ID: AIRB

//copy this line to madflight.ino to use this flight controller
#include <madflight_zzz_AIRB-AG3XF4.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-AIRB-AG3XF4"
#define HAL_MCU "STM32F405"

#define MADFLIGHT_BOARD R""(
imu_gizmo MPU6500 // #define USE_GYRO_SPI_MPU6500
imu_gizmo MPU6000 // #define USE_GYRO_SPI_MPU6000
bar_gizmo BMP280 // #define USE_BARO_BMP280
pin_out0 PC8 // resource MOTOR 1 C08
pin_out1 PB0 // resource MOTOR 2 B00
pin_out2 PB1 // resource MOTOR 3 B01
pin_out3 PB7 // resource MOTOR 4 B07
pin_out4 PB8 // resource MOTOR 5 B08
pin_out5 PC9 // resource MOTOR 6 C09
pin_out6 PB14 // resource MOTOR 7 B14
pin_out7 PB15 // resource MOTOR 8 B15
pin_rcl_ppm PA8 // resource PPM 1 A08
// resource LED_STRIP 1 A02
pin_ser0_tx PA9 // resource SERIAL_TX 1 A09
pin_ser2_tx PC10 // resource SERIAL_TX 3 C10
pin_ser4_tx PC12 // resource SERIAL_TX 5 C12
pin_ser5_tx PC6 // resource SERIAL_TX 6 C06
pin_ser0_rx PA10 // resource SERIAL_RX 1 A10
pin_ser2_rx PC11 // resource SERIAL_RX 3 C11
pin_ser3_rx PA1 // resource SERIAL_RX 4 A01
pin_ser4_rx PD2 // resource SERIAL_RX 5 D02
pin_ser5_rx PC7 // resource SERIAL_RX 6 C07
pin_i2c1_scl PB10 // resource I2C_SCL 2 B10
pin_i2c1_sda PB11 // resource I2C_SDA 2 B11
pin_led PC13 // resource LED 1 C13
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi2_sclk PB3 // resource SPI_SCK 3 B03
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi1_miso PC2 // resource SPI_MISO 2 C02
pin_spi2_miso PB4 // resource SPI_MISO 3 B04
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi1_mosi PC3 // resource SPI_MOSI 2 C03
pin_spi2_mosi PB5 // resource SPI_MOSI 3 B05
// resource ESCSERIAL 1 A08
// resource CAMERA_CONTROL 1 A03
pin_bat_v PC0 // resource ADC_BATT 1 C00
bat_gizmo ADC
// resource ADC_RSSI 1 C04
pin_bat_i PC1 // resource ADC_CURR 1 C01
bat_gizmo ADC
// resource ADC_EXT 1 A00
// resource BARO_CS 1 B09
// resource FLASH_CS 1 B12
// resource OSD_CS 1 A15
pin_imu_cs PA4 // resource GYRO_CS 1 A04
// resource GYRO_CS 2 C15
// set mag_bustype = I2C
mag_i2c_bus 1 // set mag_i2c_device = 2
// set baro_spi_device = 2
// set blackbox_device = SPIFLASH
// set dshot_burst = ON
// set current_meter = ESC
// set battery_meter = ADC
// set beeper_inversion = ON
// set beeper_od = OFF
// set system_hse_mhz = 8
// set max7456_spi_bus = 3
// set dashboard_i2c_bus = 2
// set flash_spi_bus = 2
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
imu_align CW270FLIP // set gyro_1_sensor_align = CW270FLIP
// set gyro_1_align_pitch = 1800
// set gyro_1_align_yaw = 2700
// set gyro_2_spibus = 1
// set gyro_2_sensor_align = CW0FLIP
// set gyro_2_align_pitch = 1800
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F405 (S405) 4.2.0 Feb  2 2020 / 13:54:52 (09e8234117) MSP API: 1.43
#mcu STM32F405

#define USE_GYRO
#define USE_GYRO_SPI_MPU6500
#define USE_GYRO_SPI_MPU6000
#define USE_ACC
#define USE_ACC_SPI_MPU6500
#define USE_ACC_SPI_MPU6000
#define USE_BARO
#define USE_BARO_BMP280
#define USE_MAX7456

board_name AG3XF4
manufacturer_id AIRB

# resources
resource MOTOR 1 C08
resource MOTOR 2 B00
resource MOTOR 3 B01
resource MOTOR 4 B07
resource MOTOR 5 B08
resource MOTOR 6 C09
resource MOTOR 7 B14
resource MOTOR 8 B15
resource PPM 1 A08
resource LED_STRIP 1 A02
resource SERIAL_TX 1 A09
resource SERIAL_TX 3 C10
resource SERIAL_TX 5 C12
resource SERIAL_TX 6 C06
resource SERIAL_RX 1 A10
resource SERIAL_RX 3 C11
resource SERIAL_RX 4 A01
resource SERIAL_RX 5 D02
resource SERIAL_RX 6 C07
resource I2C_SCL 2 B10
resource I2C_SDA 2 B11
resource LED 1 C13
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 B03
resource SPI_MISO 1 A06
resource SPI_MISO 2 C02
resource SPI_MISO 3 B04
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 C03
resource SPI_MOSI 3 B05
resource ESCSERIAL 1 A08
resource CAMERA_CONTROL 1 A03
resource ADC_BATT 1 C00
resource ADC_RSSI 1 C04
resource ADC_CURR 1 C01
resource ADC_EXT 1 A00
resource BARO_CS 1 B09
resource FLASH_CS 1 B12
resource OSD_CS 1 A15
resource GYRO_CS 1 A04
resource GYRO_CS 2 C15

# timer
timer A08 AF1
# pin A08: TIM1 CH1 (AF1)
timer C08 AF3
# pin C08: TIM8 CH3 (AF3)
timer B00 AF2
# pin B00: TIM3 CH3 (AF2)
timer B01 AF2
# pin B01: TIM3 CH4 (AF2)
timer B07 AF2
# pin B07: TIM4 CH2 (AF2)
timer B08 AF2
# pin B08: TIM4 CH3 (AF2)
timer C09 AF3
# pin C09: TIM8 CH4 (AF3)
timer B14 AF9
# pin B14: TIM12 CH1 (AF9)
timer B15 AF9
# pin B15: TIM12 CH2 (AF9)
timer A09 AF1
# pin A09: TIM1 CH2 (AF1)
timer A10 AF1
# pin A10: TIM1 CH3 (AF1)
timer A02 AF2
# pin A02: TIM5 CH3 (AF2)
timer A03 AF3
# pin A03: TIM9 CH2 (AF3)
timer B10 AF1
# pin B10: TIM2 CH3 (AF1)
timer B11 AF1
# pin B11: TIM2 CH4 (AF1)

# dma
dma ADC 1 1
# ADC 1: DMA2 Stream 4 Channel 0
dma pin A08 0
# pin A08: DMA2 Stream 6 Channel 0
dma pin C08 0
# pin C08: DMA2 Stream 2 Channel 0
dma pin B00 0
# pin B00: DMA1 Stream 7 Channel 5
dma pin B01 0
# pin B01: DMA1 Stream 2 Channel 5
dma pin B07 0
# pin B07: DMA1 Stream 3 Channel 2
dma pin B08 0
# pin B08: DMA1 Stream 7 Channel 2
dma pin C09 0
# pin C09: DMA2 Stream 7 Channel 7
dma pin A09 1
# pin A09: DMA2 Stream 2 Channel 6
dma pin A10 0
# pin A10: DMA2 Stream 6 Channel 0
dma pin A02 0
# pin A02: DMA1 Stream 0 Channel 6
dma pin B10 0
# pin B10: DMA1 Stream 1 Channel 3
dma pin B11 0
# pin B11: DMA1 Stream 7 Channel 3

# feature
feature OSD

# master
set mag_bustype = I2C
set mag_i2c_device = 2
set baro_spi_device = 2
set blackbox_device = SPIFLASH
set dshot_burst = ON
set current_meter = ESC
set battery_meter = ADC
set beeper_inversion = ON
set beeper_od = OFF
set system_hse_mhz = 8
set max7456_spi_bus = 3
set dashboard_i2c_bus = 2
set flash_spi_bus = 2
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW270FLIP
set gyro_1_align_pitch = 1800
set gyro_1_align_yaw = 2700
set gyro_2_spibus = 1
set gyro_2_sensor_align = CW0FLIP
set gyro_2_align_pitch = 1800

*/
