/*==============================================================================
Generated on: 2025-03-18 18:40:43.336164
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: EMAX_TINYHAWK_F411RX
Manufacturer ID: EMAX

//copy this line to madflight.ino to use this flight controller
#include <madflight_board_EMAX-EMAX_TINYHAWK_F411RX.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-EMAX-EMAX_TINYHAWK_F411RX"
#define HAL_MCU "STM32F411"

#define MADFLIGHT_BOARD R""(
imu_gizmo MPU6000 // #define USE_GYRO_SPI_MPU6000
imu_gizmo ICM20689 // #define USE_GYRO_SPI_ICM20689
// resource BEEPER 1 C15
pin_out0 PB10 // resource MOTOR 1 B10
pin_out1 PB6 // resource MOTOR 2 B06
pin_out2 PB7 // resource MOTOR 3 B07
pin_out3 PB8 // resource MOTOR 4 B08
pin_rcl_ppm PA3 // resource PPM 1 A03
// resource PWM 1 A02
// resource PWM 2 A09
// resource PWM 3 A10
// resource LED_STRIP 1 A00
pin_ser0_tx PA9 // resource SERIAL_TX 1 A09
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser0_rx PA10 // resource SERIAL_RX 1 A10
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_led PC13 // resource LED 1 C13
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi1_sclk PB13 // resource SPI_SCK 2 B13
pin_spi2_sclk PB3 // resource SPI_SCK 3 B03
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi1_miso PB14 // resource SPI_MISO 2 B14
pin_spi2_miso PB4 // resource SPI_MISO 3 B04
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi1_mosi PB15 // resource SPI_MOSI 2 B15
pin_spi2_mosi PB5 // resource SPI_MOSI 3 B05
pin_bat_v PB0 // resource ADC_BATT 1 B00
bat_gizmo ADC
pin_bat_i PB1 // resource ADC_CURR 1 B01
bat_gizmo ADC
// resource OSD_CS 1 B12
// resource RX_SPI_CS 1 A15
// resource RX_SPI_EXTI 1 C14
// resource RX_SPI_BIND 1 B02
// resource RX_SPI_LED 1 B09
// resource RX_SPI_CC2500_TX_EN 1 A08
// resource RX_SPI_CC2500_LNA_EN 1 A13
// resource RX_SPI_CC2500_ANT_SEL 1 A14
pin_imu_int PA1 // resource GYRO_EXTI 1 A01
pin_imu_cs PA4 // resource GYRO_CS 1 A04
// set rx_spi_protocol = FRSKY_X
// set rx_spi_bus = 3
// set rx_spi_led_inversion = ON
// set dshot_burst = AUTO
// set current_meter = ADC
// set battery_meter = ADC
// set ibata_scale = 179
// set beeper_inversion = ON
// set beeper_od = OFF
// set system_hse_mhz = 8
// set max7456_spi_bus = 2
// set cc2500_spi_chip_detect = OFF
// set gyro_1_bustype = SPI
imu_spi_bus 0 // set gyro_1_spibus = 1
imu_align CW180 // set gyro_1_sensor_align = CW180
// set gyro_2_spibus = 1
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F411 (S411) 4.1.0 Oct 16 2019 / 11:57:34 (c37a7c91a) MSP API: 1.42

board_name EMAX_TINYHAWK_F411RX
manufacturer_id EMAX

#define USE_GYRO
#define USE_GYRO_SPI_MPU6000
#define USE_ACC
#define USE_ACC_SPI_MPU6000
#define USE_ACCGYRO_BMI270
#define USE_GYRO_SPI_ICM20689
#define USE_ACC_SPI_ICM20689
#define USE_RX_CC2500
#define USE_MAX7456

# resources
resource BEEPER 1 C15
resource MOTOR 1 B10
resource MOTOR 2 B06
resource MOTOR 3 B07
resource MOTOR 4 B08
resource PPM 1 A03
resource PWM 1 A02
resource PWM 2 A09
resource PWM 3 A10
resource LED_STRIP 1 A00
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 A03
resource LED 1 C13
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 3 B03
resource SPI_MISO 1 A06
resource SPI_MISO 2 B14
resource SPI_MISO 3 B04
resource SPI_MOSI 1 A07
resource SPI_MOSI 2 B15
resource SPI_MOSI 3 B05
resource ADC_BATT 1 B00
resource ADC_CURR 1 B01
resource OSD_CS 1 B12
resource RX_SPI_CS 1 A15
resource RX_SPI_EXTI 1 C14
resource RX_SPI_BIND 1 B02
resource RX_SPI_LED 1 B09
resource RX_SPI_CC2500_TX_EN 1 A08
resource RX_SPI_CC2500_LNA_EN 1 A13
resource RX_SPI_CC2500_ANT_SEL 1 A14
resource GYRO_EXTI 1 A01
resource GYRO_CS 1 A04

# timer
timer A03 AF3
# pin A03: TIM9 CH2 (AF3)
timer B10 AF1
# pin B10: TIM2 CH3 (AF1)
timer B06 AF2
# pin B06: TIM4 CH1 (AF2)
timer B07 AF2
# pin B07: TIM4 CH2 (AF2)
timer B08 AF2
# pin B08: TIM4 CH3 (AF2)
timer A00 AF2
# pin A00: TIM5 CH1 (AF2)
timer A02 AF3
# pin A02: TIM9 CH1 (AF3)
timer A09 AF1
# pin A09: TIM1 CH2 (AF1)
timer A10 AF1
# pin A10: TIM1 CH3 (AF1)

# dma
dma ADC 1 0
# ADC 1: DMA2 Stream 0 Channel 0
dma pin B10 0
# pin B10: DMA1 Stream 1 Channel 3
dma pin B06 0
# pin B06: DMA1 Stream 0 Channel 2
dma pin B07 0
# pin B07: DMA1 Stream 3 Channel 2
dma pin B08 0
# pin B08: DMA1 Stream 7 Channel 2
dma pin A00 0
# pin A00: DMA1 Stream 2 Channel 6
dma pin A09 0
# pin A09: DMA2 Stream 6 Channel 0
dma pin A10 0
# pin A10: DMA2 Stream 6 Channel 0

# feature
feature RX_SPI
feature OSD

# master
set rx_spi_protocol = FRSKY_X
set rx_spi_bus = 3
set rx_spi_led_inversion = ON
set dshot_burst = AUTO
set current_meter = ADC
set battery_meter = ADC
set ibata_scale = 179
set beeper_inversion = ON
set beeper_od = OFF
set system_hse_mhz = 8
set max7456_spi_bus = 2
set cc2500_spi_chip_detect = OFF
set gyro_1_bustype = SPI
set gyro_1_spibus = 1
set gyro_1_sensor_align = CW180
set gyro_2_spibus = 1

*/
