/*==============================================================================
Generated on: 2025-03-18 18:40:43.527544
Generated by: betaflight_target_converter.py
Source: https://github.com/betaflight/unified-targets
Board name: NBD_INFINITYAIO255
Manufacturer ID: NEBD

//copy this line to madflight.ino to use this flight controller
#include <madflight_board_NEBD-NBD_INFINITYAIO255.h>

Note: madflight will pick the last sensor defined here, this might not be the sensor that is actually on the board. Comment the offending sensors out.
==============================================================================*/

#define HAL_BOARD_NAME "BETAFLIGHT-NEBD-NBD_INFINITYAIO255"
#define HAL_MCU "STM32F745"

#define MADFLIGHT_BOARD R""(
imu_gizmo MPU6000 // #define USE_GYRO_SPI_MPU6000
// resource BEEPER 1 D13
pin_out0 PC9 // resource MOTOR 1 C09
pin_out1 PC8 // resource MOTOR 2 C08
pin_out2 PC7 // resource MOTOR 3 C07
pin_out3 PC6 // resource MOTOR 4 C06
// resource LED_STRIP 1 A09
pin_ser1_tx PA2 // resource SERIAL_TX 2 A02
pin_ser2_tx PB10 // resource SERIAL_TX 3 B10
pin_ser6_tx PE8 // resource SERIAL_TX 7 E08
pin_ser7_tx PE1 // resource SERIAL_TX 8 E01
pin_ser0_rx PB7 // resource SERIAL_RX 1 B07
pin_ser1_rx PA3 // resource SERIAL_RX 2 A03
pin_ser2_rx PB11 // resource SERIAL_RX 3 B11
pin_ser4_rx PD2 // resource SERIAL_RX 5 D02
pin_ser7_rx PE0 // resource SERIAL_RX 8 E00
pin_i2c0_scl PB8 // resource I2C_SCL 1 B08
pin_i2c0_sda PB9 // resource I2C_SDA 1 B09
pin_led PC0 // resource LED 1 C00
pin_spi0_sclk PA5 // resource SPI_SCK 1 A05
pin_spi2_sclk PB3 // resource SPI_SCK 3 B03
pin_spi3_sclk PE12 // resource SPI_SCK 4 E12
pin_spi0_miso PA6 // resource SPI_MISO 1 A06
pin_spi2_miso PB4 // resource SPI_MISO 3 B04
pin_spi3_miso PE13 // resource SPI_MISO 4 E13
pin_spi0_mosi PA7 // resource SPI_MOSI 1 A07
pin_spi2_mosi PD6 // resource SPI_MOSI 3 D06
pin_spi3_mosi PE14 // resource SPI_MOSI 4 E14
pin_bat_v PC1 // resource ADC_BATT 1 C01
bat_gizmo ADC
pin_bat_i PC2 // resource ADC_CURR 1 C02
bat_gizmo ADC
// resource FLASH_CS 1 B00
// resource OSD_CS 1 A15
pin_imu_int PB1 // resource GYRO_EXTI 1 B01
pin_imu_cs PE11 // resource GYRO_CS 1 E11
// set baro_bustype = I2C
bar_i2c_bus 0 // set baro_i2c_device = 1
// set mag_bustype = I2C
mag_i2c_bus 0 // set mag_i2c_device = 1
// set blackbox_device = SPIFLASH
// set dshot_burst = ON
// set current_meter = ADC
// set battery_meter = ADC
// set ibata_scale = 100
// set beeper_inversion = ON
// set beeper_od = OFF
// set beeper_frequency = 5400
// set max7456_spi_bus = 3
// set flash_spi_bus = 1
imu_spi_bus 3 // set gyro_1_spibus = 4
imu_align CW180 // set gyro_1_sensor_align = CW180
// set gyro_1_align_yaw = 1800
)"" //end of MADFLIGHT_BOARD


/*
#==============================================================================
# BetaFlight Source file
#==============================================================================
# Betaflight / STM32F745 (S745) 4.4.2 May 31 2023 / 22:53:35 (23d066d) MSP API: 1.45

#define USE_ACC
#define USE_ACC_SPI_MPU6000
#define USE_GYRO
#define USE_GYRO_SPI_MPU6000
#define USE_FLASH
#define USE_FLASH_W25Q128FV
#define USE_MAX7456

board_name NBD_INFINITYAIO255
manufacturer_id NEBD

# resources
resource BEEPER 1 D13
resource MOTOR 1 C09
resource MOTOR 2 C08
resource MOTOR 3 C07
resource MOTOR 4 C06
resource LED_STRIP 1 A09
resource SERIAL_TX 2 A02
resource SERIAL_TX 3 B10
resource SERIAL_TX 7 E08
resource SERIAL_TX 8 E01
resource SERIAL_RX 1 B07
resource SERIAL_RX 2 A03
resource SERIAL_RX 3 B11
resource SERIAL_RX 5 D02
resource SERIAL_RX 8 E00
resource I2C_SCL 1 B08
resource I2C_SDA 1 B09
resource LED 1 C00
resource SPI_SCK 1 A05
resource SPI_SCK 3 B03
resource SPI_SCK 4 E12
resource SPI_MISO 1 A06
resource SPI_MISO 3 B04
resource SPI_MISO 4 E13
resource SPI_MOSI 1 A07
resource SPI_MOSI 3 D06
resource SPI_MOSI 4 E14
resource ADC_BATT 1 C01
resource ADC_CURR 1 C02
resource FLASH_CS 1 B00
resource OSD_CS 1 A15
resource GYRO_EXTI 1 B01
resource GYRO_CS 1 E11

# timer
timer C09 AF2
# pin C09: TIM3 CH4 (AF2)
timer C08 AF2
# pin C08: TIM3 CH3 (AF2)
timer C07 AF2
# pin C07: TIM3 CH2 (AF2)
timer C06 AF2
# pin C06: TIM3 CH1 (AF2)
timer A09 AF1
# pin A09: TIM1 CH2 (AF1)
timer D13 AF2
# pin D13: TIM4 CH2 (AF2)

# dma
dma ADC 1 0
# ADC 1: DMA2 Stream 0 Channel 0
dma pin C09 0
# pin C09: DMA1 Stream 2 Channel 5
dma pin C08 0
# pin C08: DMA1 Stream 7 Channel 5
dma pin C07 0
# pin C07: DMA1 Stream 5 Channel 5
dma pin C06 0
# pin C06: DMA1 Stream 4 Channel 5
dma pin A09 0
# pin A09: DMA2 Stream 6 Channel 0
dma pin D13 0
# pin D13: DMA1 Stream 3 Channel 2

# feature
feature OSD
feature ESC_SENSOR

# serial
serial 1 131073 115200 57600 0 115200
serial 2 2 115200 57600 0 115200
serial 4 1024 115200 57600 0 115200
serial 7 64 115200 57600 0 115200

# master
set baro_bustype = I2C
set baro_i2c_device = 1
set mag_bustype = I2C
set mag_i2c_device = 1
set blackbox_device = SPIFLASH
set dshot_burst = ON
set current_meter = ADC
set battery_meter = ADC
set ibata_scale = 100
set beeper_inversion = ON
set beeper_od = OFF
set beeper_frequency = 5400
set max7456_spi_bus = 3
set flash_spi_bus = 1
set gyro_1_spibus = 4
set gyro_1_sensor_align = CW180
set gyro_1_align_yaw = 1800

*/
